// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtC0oQJnO_L0rIkLgretBdlpkN4JFnTUU',
    appId: '1:732150307261:web:a3205750875968c2f15ad4',
    messagingSenderId: '732150307261',
    projectId: 'amar-dokan-flutter-app',
    authDomain: 'amar-dokan-flutter-app.firebaseapp.com',
    storageBucket: 'amar-dokan-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW4h3SQ-rARwoedkHMTz0mApd16n1CXus',
    appId: '1:732150307261:android:fde216060f15afc1f15ad4',
    messagingSenderId: '732150307261',
    projectId: 'amar-dokan-flutter-app',
    storageBucket: 'amar-dokan-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoS1VRfdIIdwsdgm7LBvpa8KRW7VuduEE',
    appId: '1:732150307261:ios:4a53a0eb52ba9ebaf15ad4',
    messagingSenderId: '732150307261',
    projectId: 'amar-dokan-flutter-app',
    storageBucket: 'amar-dokan-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.invosisFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoS1VRfdIIdwsdgm7LBvpa8KRW7VuduEE',
    appId: '1:732150307261:ios:4a53a0eb52ba9ebaf15ad4',
    messagingSenderId: '732150307261',
    projectId: 'amar-dokan-flutter-app',
    storageBucket: 'amar-dokan-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.invosisFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtC0oQJnO_L0rIkLgretBdlpkN4JFnTUU',
    appId: '1:732150307261:web:16971710d3f55418f15ad4',
    messagingSenderId: '732150307261',
    projectId: 'amar-dokan-flutter-app',
    authDomain: 'amar-dokan-flutter-app.firebaseapp.com',
    storageBucket: 'amar-dokan-flutter-app.firebasestorage.app',
  );
}
